font_family         JetBrainsMono Nerd Font
font_size           12.0

shell               zsh

tab_bar_style       powerline
tab_powerline_style slanted
tab_separator       " ┇"

active_tab_font_style bold
inactive_tab_font_style normal

window_padding_width 8
background_opacity 1.0

confirm_os_window_close 0

enable_audio_bell no
visual_bell_duration 0

cursor_trail 1
cursor_trail_decay 0.1 0.4

disable_ligatures never

remember_window_size yes

# Optional smoothness
resize_debounce_time 0.1

# GPU rendering tweaks
repaint_delay       8
input_delay         1

# BEGIN_KITTY_THEME
# ANSI 1987
include nord-theme.conf
# END_KITTY_THEME
