---
- name: Paperless.conf deployen
  ansible.builtin.template:
    src: paperless.conf.j2
    dest: /opt/paperless/paperless.conf
    owner: root
    group: root
    mode: '0640'
  notify: paperless neu starten
