---
- name: Zabbix-agent2 neu starten
  ansible.builtin.service:
    name: zabbix-agent2
    state: restarted

- name: Frigate neu starten
  community.docker.docker_compose_v2:
    project_src: /opt/frigate
    state: present
    recreate: always
