---
- name: NPMplus Verzeichnis erstellen
  ansible.builtin.file:
    path: /opt
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Compose.yaml deployen
  ansible.builtin.template:
    src: compose.yaml.j2
    dest: /opt/compose.yaml
    owner: root
    group: root
    mode: '0644'
