---
- name: Keepalived installieren
  ansible.builtin.package:
    name: keepalived
    state: present

- name: Keepalived.conf deployen
  ansible.builtin.template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    owner: root
    group: root
    mode: '0644'
  notify: keepalived neu starten

- name: Keepalived service aktivieren
  ansible.builtin.service:
    name: keepalived
    state: started
    enabled: true

- name: Zabbix UserParameter für keepalived deployen
  ansible.builtin.copy:
    src: keepalived.conf
    dest: /etc/zabbix/zabbix_agent2.d/keepalived.conf
    owner: root
    group: zabbix
    mode: '0640'
  notify: zabbix-agent2 neu starten
