---
- name: Zabbix Agent 2 installieren
  ansible.builtin.package:
    name: zabbix-agent2
    state: present

- name: zabbix_agent2.conf deployen
  ansible.builtin.template:
    src: zabbix_agent2.conf.j2
    dest: /etc/zabbix/zabbix_agent2.conf
    owner: root
    group: zabbix
    mode: '0640'
  notify: zabbix-agent2 neu starten

- name: zabbix-agent2 service aktivieren
  ansible.builtin.service:
    name: zabbix-agent2
    state: started
    enabled: true
