---
- name: Zshrc deployen
  ansible.builtin.template:
    src: zshrc.j2
    dest: "{{ ansible_facts['env']['HOME'] }}/.zshrc"
    owner: "{{ ansible_facts['user_id'] }}"
    mode: '0644'

- name: Kitty Config-Verzeichnis erstellen
  ansible.builtin.file:
    path: "{{ ansible_facts['env']['HOME'] }}/.config/kitty"
    state: directory
    mode: '0755'

- name: Kitty.conf deployen
  ansible.builtin.copy:
    src: kitty.conf
    dest: "{{ ansible_facts['env']['HOME'] }}/.config/kitty/kitty.conf"
    owner: "{{ ansible_facts['user_id'] }}"
    mode: '0644'

- name: Starship.toml deployen
  ansible.builtin.template:
    src: starship.toml.j2
    dest: "{{ ansible_facts['env']['HOME'] }}/.config/starship.toml"
    owner: "{{ ansible_facts['user_id'] }}"
    mode: '0644'

- name: GnuPG-Verzeichnis erstellen
  ansible.builtin.file:
    path: "{{ ansible_facts['env']['HOME'] }}/.gnupg"
    state: directory
    mode: '0700'

- name: Gpg-agent.conf deployen
  ansible.builtin.copy:
    src: gpg-agent.conf
    dest: "{{ ansible_facts['env']['HOME'] }}/.gnupg/gpg-agent.conf"
    owner: "{{ ansible_facts['user_id'] }}"
    mode: '0600'

- name: Scdaemon.conf deployen
  ansible.builtin.copy:
    src: scdaemon.conf
    dest: "{{ ansible_facts['env']['HOME'] }}/.gnupg/scdaemon.conf"
    owner: "{{ ansible_facts['user_id'] }}"
    mode: '0600'
