UserParameter=frigate.version.installed,curl -s http://127.0.0.1:5000/api/version | cut -d'-' -f1
UserParameter=frigate.version.latest,curl -s https://api.github.com/repos/blakeblackshear/frigate/releases/latest | jq -r .tag_name | sed 's/^v//'
UserParameter=frigate.container.status,docker inspect --format='{{.State.Status}}' frigate
UserParameter=frigate.container.health,docker inspect --format='{{.State.Health.Status}}' frigate
UserParameter=frigate.container.health.numeric,[ "$(docker inspect --format='{{.State.Health.Status}}' frigate)" = "healthy" ] && echo 1 || echo 0
UserParameter=frigate.container.status.numeric,[ "$(docker inspect --format='{{.State.Status}}' frigate)" = "running" ] && echo 1 || echo 0
UserParameter=frigate.detection_fps,curl -s http://127.0.0.1:5000/api/stats | jq '.detection_fps'
UserParameter=frigate.coral.inference_speed,curl -s http://127.0.0.1:5000/api/stats | jq '.detectors.coral.inference_speed'
UserParameter=frigate.gpu.usage,curl -s http://127.0.0.1:5000/api/stats | jq -r '.gpu_usages["intel-vaapi"].gpu' | tr -d '%'
