---
- name: zabbix_server.conf deployen
  ansible.builtin.template:
    src: zabbix_server.conf.j2
    dest: /etc/zabbix/zabbix_server.conf
    owner: root
    group: zabbix
    mode: '0640'
  notify: zabbix-server neu starten
